(ns faceboard.helpers.countries
  (:require [faceboard.logging :refer [log log-err log-warn log-info]]))

(def country-names
  {"nl" ["Netherlands"]
   "aw" ["Aruba"]
   "bl" ["Saint Barthelemy"]
   "zw" ["Zimbabwe"]
   "us" ["United States"]
   "cg" ["Republic of the Congo"]
   "ee" ["Estonia"]
   "im" ["Isle of Man"]
   "pf" ["French Polynesia"]
   "ec" ["Ecuador"]
   "st" ["Sao Tome and Principe"]
   "mh" ["Marshall Islands"]
   "gm" ["Gambia"]
   "kh" ["Cambodia"]
   "td" ["Chad"]
   "xk" ["Kosovo"]
   "pt" ["Portugal"]
   "hk" ["Hong Kong"]
   "la" ["Laos"]
   "bz" ["Belize"]
   "br" ["Brazil"]
   "rs" ["Serbia"]
   "tg" ["Togo"]
   "jm" ["Jamaica"]
   "wf" ["Wallis and Futuna"]
   "ht" ["Haiti"]
   "rw" ["Rwanda"]
   "ls" ["Lesotho"]
   "md" ["Moldova"]
   "lv" ["Latvia"]
   "lt" ["Lithuania"]
   "ad" ["Andorra"]
   "cy" ["Cyprus"]
   "yt" ["Mayotte"]
   "ne" ["Niger"]
   "al" ["Albania"]
   "pw" ["Palau"]
   "mo" ["Macao"]
   "sr" ["Suriname"]
   "gw" ["Guinea-Bissau"]
   "ro" ["Romania"]
   "ua" ["Ukraine"]
   "pg" ["Papua New Guinea"]
   "ck" ["Cook Islands"]
   "pe" ["Peru"]
   "vc" ["Saint Vincent and the Grenadines"]
   "cn" ["China"]
   "cw" ["Curacao"]
   "tr" ["Turkey"]
   "cz" ["Czech Republic"]
   "nf" ["Norfolk Island"]
   "ch" ["Switzerland"]
   "ci" ["Ivory Coast"]
   "ss" ["South Sudan"]
   "kr" ["South Korea"]
   "it" ["Italy"]
   "gg" ["Guernsey"]
   "nu" ["Niue"]
   "mv" ["Maldives"]
   "bt" ["Bhutan"]
   "hn" ["Honduras"]
   "by" ["Belarus"]
   "cf" ["Central African Republic"]
   "py" ["Paraguay"]
   "ps" ["Palestinian Territory"]
   "bw" ["Botswana"]
   "is" ["Iceland"]
   "bs" ["Bahamas"]
   "tj" ["Tajikistan"]
   "vg" ["British Virgin Islands"]
   "dz" ["Algeria"]
   "sx" ["Sint Maarten"]
   "fm" ["Micronesia"]
   "nc" ["New Caledonia"]
   "bo" ["Bolivia"]
   "om" ["Oman"]
   "ky" ["Cayman Islands"]
   "vi" ["U.S. Virgin Islands"]
   "sn" ["Senegal"]
   "vn" ["Vietnam"]
   "dm" ["Dominica"]
   "gq" ["Equatorial Guinea"]
   "ki" ["Kiribati"]
   "lr" ["Liberia"]
   "iq" ["Iraq"]
   "sc" ["Seychelles"]
   "ax" ["Aland Islands"]
   "id" ["Indonesia"]
   "mm" ["Myanmar"]
   "bf" ["Burkina Faso"]
   "sy" ["Syria"]
   "tw" ["Taiwan"]
   "tf" ["French Southern Territories"]
   "cr" ["Costa Rica"]
   "tt" ["Trinidad and Tobago"]
   "bq" ["Bonaire, Saint Eustatius and Saba "]
   "pl" ["Poland"]
   "tl" ["East Timor"]
   "my" ["Malaysia"]
   "er" ["Eritrea"]
   "co" ["Colombia"]
   "fi" ["Finland"]
   "gs" ["South Georgia and the South Sandwich Islands"]
   "bm" ["Bermuda"]
   "gt" ["Guatemala"]
   "mc" ["Monaco"]
   "ly" ["Libya"]
   "ca" ["Canada"]
   "hm" ["Heard Island and McDonald Islands"]
   "sv" ["El Salvador"]
   "si" ["Slovenia"]
   "ug" ["Uganda"]
   "gb" ["United Kingdom"]
   "gh" ["Ghana"]
   "hr" ["Croatia"]
   "io" ["British Indian Ocean Territory"]
   "gn" ["Guinea"]
   "sl" ["Sierra Leone"]
   "sa" ["Saudi Arabia"]
   "ir" ["Iran"]
   "fr" ["France"]
   "kn" ["Saint Kitts and Nevis"]
   "bi" ["Burundi"]
   "nz" ["New Zealand"]
   "ma" ["Morocco"]
   "ni" ["Nicaragua"]
   "bd" ["Bangladesh"]
   "bn" ["Brunei"]
   "mk" ["Macedonia"]
   "sb" ["Solomon Islands"]
   "sg" ["Singapore"]
   "ms" ["Montserrat"]
   "af" ["Afghanistan"]
   "cd" ["Democratic Republic of the Congo"]
   "vu" ["Vanuatu"]
   "gu" ["Guam"]
   "il" ["Israel"]
   "tv" ["Tuvalu"]
   "ph" ["Philippines"]
   "an" ["Netherlands Antilles"]
   "eh" ["Western Sahara"]
   "tn" ["Tunisia"]
   "ml" ["Mali"]
   "hu" ["Hungary"]
   "de" ["Germany"]
   "dk" ["Denmark"]
   "am" ["Armenia"]
   "um" ["United States Minor Outlying Islands"]
   "so" ["Somalia"]
   "kw" ["Kuwait"]
   "ru" ["Russia"]
   "sk" ["Slovakia"]
   "mz" ["Mozambique"]
   "kz" ["Kazakhstan"]
   "ga" ["Gabon"]
   "sj" ["Svalbard and Jan Mayen"]
   "pm" ["Saint Pierre and Miquelon"]
   "zm" ["Zambia"]
   "ye" ["Yemen"]
   "dj" ["Djibouti"]
   "bh" ["Bahrain"]
   "bv" ["Bouvet Island"]
   "pn" ["Pitcairn"]
   "be" ["Belgium"]
   "se" ["Sweden"]
   "uz" ["Uzbekistan"]
   "es" ["Spain"]
   "ba" ["Bosnia and Herzegovina"]
   "ai" ["Anguilla"]
   "np" ["Nepal"]
   "gf" ["French Guiana"]
   "ng" ["Nigeria"]
   "cl" ["Chile"]
   "mt" ["Malta"]
   "ge" ["Georgia"]
   "tk" ["Tokelau"]
   "do" ["Dominican Republic"]
   "cu" ["Cuba"]
   "fk" ["Falkland Islands"]
   "lc" ["Saint Lucia"]
   "sz" ["Swaziland"]
   "lb" ["Lebanon"]
   "km" ["Comoros"]
   "gl" ["Greenland"]
   "ae" ["United Arab Emirates"]
   "jp" ["Japan"]
   "za" ["South Africa"]
   "mu" ["Mauritius"]
   "et" ["Ethiopia"]
   "ag" ["Antigua and Barbuda"]
   "gr" ["Greece"]
   "aq" ["Antarctica"]
   "kg" ["Kyrgyzstan"]
   "tm" ["Turkmenistan"]
   "ke" ["Kenya"]
   "kp" ["North Korea"]
   "mx" ["Mexico"]
   "ie" ["Ireland"]
   "mr" ["Mauritania"]
   "mn" ["Mongolia"]
   "uy" ["Uruguay"]
   "cs" ["Serbia and Montenegro"]
   "tc" ["Turks and Caicos Islands"]
   "no" ["Norway"]
   "cv" ["Cape Verde"]
   "mw" ["Malawi"]
   "sh" ["Saint Helena"]
   "eg" ["Egypt"]
   "re" ["Reunion"]
   "ar" ["Argentina"]
   "bg" ["Bulgaria"]
   "bb" ["Barbados"]
   "sd" ["Sudan"]
   "gi" ["Gibraltar"]
   "cx" ["Christmas Island"]
   "ve" ["Venezuela"]
   "fo" ["Faroe Islands"]
   "na" ["Namibia"]
   "to" ["Tonga"]
   "gp" ["Guadeloupe"]
   "pa" ["Panama"]
   "mq" ["Martinique"]
   "mg" ["Madagascar"]
   "ws" ["Samoa"]
   "jo" ["Jordan"]
   "tz" ["Tanzania"]
   "th" ["Thailand"]
   "je" ["Jersey"]
   "sm" ["San Marino"]
   "va" ["Vatican"]
   "as" ["American Samoa"]
   "pr" ["Puerto Rico"]
   "me" ["Montenegro"]
   "at" ["Austria"]
   "gd" ["Grenada"]
   "fj" ["Fiji"]
   "li" ["Liechtenstein"]
   "cm" ["Cameroon"]
   "au" ["Australia"]
   "gy" ["Guyana"]
   "cc" ["Cocos Islands"]
   "bj" ["Benin"]
   "pk" ["Pakistan"]
   "lu" ["Luxembourg"]
   "ao" ["Angola"]
   "qa" ["Qatar"]
   "mp" ["Northern Mariana Islands"]
   "in" ["India"]
   "nr" ["Nauru"]
   "az" ["Azerbaijan"]
   "mf" ["Saint Martin"]
   "lk" ["Sri Lanka"]})

(defn lookup-country-name [country-code]
  (first (get country-names country-code)))